export const TRENDING_TOPICS = [
  { name: "Quantum computing", tag: "Science" },
  { name: "CRISPR gene editing", tag: "Biology" },
  { name: "Dark matter", tag: "Physics" },
  { name: "The Silk Road", tag: "History" },
  { name: "Octopus intelligence", tag: "Nature" },
  { name: "Stoic philosophy", tag: "Ideas" },
  { name: "Fermentation", tag: "Food" },
  { name: "Game theory", tag: "Maths" },
  { name: "Mycology", tag: "Nature" },
  { name: "Behavioral economics", tag: "Ideas" },
];

export const EXPLORE_TOPICS = [
  "The science of sleep",
  "Black holes",
  "How vaccines work",
  "Roman engineering",
  "The psychology of habits",
  "History of cryptography",
  "Plate tectonics",
  "The Turing test",
  "Fermi paradox",
  "Renaissance painting techniques",
  "How memory works",
  "Deep sea creatures",
  "The history of jazz",
  "Quantum entanglement",
  "Viking exploration",
  "The human microbiome",
  "Epigenetics",
  "The Voynich manuscript",
  "Chaos theory",
  "Origami mathematics",
  "The placebo effect",
  "Biomimicry",
  "The Antikythera mechanism",
  "Bioluminescence",
  "The Dutch tulip mania",
  "Antibiotic resistance",
  "The Library of Alexandria",
  "Birdsong dialects",
  "Cryptic crosswords",
  "The Great Filter",
  "Volcanic winters",
  "The history of maps",
  "Sourdough starters",
  "Nuclear fusion",
  "Whale migration",
  "The invention of zero",
];
